package mybatis.dao;

import java.util.List;
import mybatis.model.Band;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int insert(Band record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    Band selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    List<Band> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int updateByPrimaryKey(Band record);
}