package mybatis.dao;

import java.util.List;
import mybatis.model.Genre;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int insert(Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    Genre selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    List<Genre> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int updateByPrimaryKey(Genre record);
}