package mybatis.dao;

import java.util.List;
import mybatis.model.Song;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    Song selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    List<Song> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int updateByPrimaryKey(Song record);
}