package mybatis.dao;

import java.util.List;
import mybatis.model.SongGenre;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SongGenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG_GENRE
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    int insert(SongGenre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG_GENRE
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    List<SongGenre> selectAll();
}