package mybatis.model;

public class Band {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BAND.ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BAND.NAME
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BAND.ID
     *
     * @return the value of PUBLIC.BAND.ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BAND.ID
     *
     * @param id the value for PUBLIC.BAND.ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BAND.NAME
     *
     * @return the value of PUBLIC.BAND.NAME
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BAND.NAME
     *
     * @param name the value for PUBLIC.BAND.NAME
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }
}