package mybatis.model;

public class SongGenre {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private Long songsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private Long genresId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @return the value of PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public Long getSongsId() {
        return songsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @param songsId the value for PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setSongsId(Long songsId) {
        this.songsId = songsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @return the value of PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public Long getGenresId() {
        return genresId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @param genresId the value for PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setGenresId(Long genresId) {
        this.genresId = genresId;
    }
}