package mybatis.model;

public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.DURATION
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private Long duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.LYRICS
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private String lyrics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.NAME
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.BAND_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    private Long bandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ID
     *
     * @return the value of PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ID
     *
     * @param id the value for PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.DURATION
     *
     * @return the value of PUBLIC.SONG.DURATION
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.DURATION
     *
     * @param duration the value for PUBLIC.SONG.DURATION
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.LYRICS
     *
     * @return the value of PUBLIC.SONG.LYRICS
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public String getLyrics() {
        return lyrics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.LYRICS
     *
     * @param lyrics the value for PUBLIC.SONG.LYRICS
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setLyrics(String lyrics) {
        this.lyrics = lyrics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.NAME
     *
     * @return the value of PUBLIC.SONG.NAME
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.NAME
     *
     * @param name the value for PUBLIC.SONG.NAME
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.BAND_ID
     *
     * @return the value of PUBLIC.SONG.BAND_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public Long getBandId() {
        return bandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.BAND_ID
     *
     * @param bandId the value for PUBLIC.SONG.BAND_ID
     *
     * @mbg.generated Tue Apr 09 22:49:33 EEST 2024
     */
    public void setBandId(Long bandId) {
        this.bandId = bandId;
    }
}